name: Snyk Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node dependencies
        run: npm install
      - name: Snyk Scan
        uses: snyk/actions/node@v1
        with:
          command: test
        env:
          SNYK_TOKEN: c0530c54-2073-458c-a63d-f2c518a6b58b
